// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/amalmadhu06/project-laptop-store-clean-arch/pkg/api"
	"github.com/amalmadhu06/project-laptop-store-clean-arch/pkg/api/handler"
	"github.com/amalmadhu06/project-laptop-store-clean-arch/pkg/config"
	"github.com/amalmadhu06/project-laptop-store-clean-arch/pkg/db"
	"github.com/amalmadhu06/project-laptop-store-clean-arch/pkg/repository"
	"github.com/amalmadhu06/project-laptop-store-clean-arch/pkg/usecase"
)

// Injectors from wire.go:

func InitializeAPI(cfg config.Config) (*http.ServerHTTP, error) {
	gormDB, err := db.ConnectDatabase(cfg)
	if err != nil {
		return nil, err
	}
	userRepository := repository.NewUserRepository(gormDB)
	orderRepository := repository.NewOrderRepository(gormDB)
	userUseCase := usecase.NewUserUseCase(userRepository, orderRepository)
	userHandler := handler.NewUserHandler(userUseCase)
	adminRepository := repository.NewAdminRepository(gormDB)
	adminUseCase := usecase.NewAdminUseCase(adminRepository, orderRepository)
	adminHandler := handler.NewAdminHandler(adminUseCase)
	otpRepository := repository.NewOtpRepository(gormDB)
	otpUseCase := usecase.NewOtpUseCase(otpRepository, cfg)
	otpHandler := handler.NewOtpHandler(otpUseCase)
	productRepository := repository.NewProductRepository(gormDB)
	productUseCase := usecase.NewProductUseCase(productRepository)
	productHandler := handler.NewProductHandler(productUseCase)
	cartRepository := repository.NewCartRepository(gormDB)
	cartUseCases := usecase.NewCartUseCase(cartRepository, productRepository)
	cartHandler := handler.NewCartHandler(cartUseCases)
	orderUseCases := usecase.NewOrderUseCase(orderRepository, userRepository, productRepository)
	orderHandler := handler.NewOrderHandler(orderUseCases)
	paymentRepository := repository.NewPaymentRepository(gormDB)
	paymentUseCases := usecase.NewPaymentUseCase(orderRepository, paymentRepository)
	paymentHandler := handler.NewPaymentHandler(paymentUseCases)
	wishlistRepository := repository.NewWishlistRepository(gormDB)
	wishlistUseCase := usecase.NewWishlistUsecase(wishlistRepository)
	wishlistHandler := handler.NewWishlistHandler(wishlistUseCase)
	serverHTTP := http.NewServerHTTP(userHandler, adminHandler, otpHandler, productHandler, cartHandler, orderHandler, paymentHandler, wishlistHandler)
	return serverHTTP, nil
}
